language: python
python:
- "3.6"
services: docker
env:
  global:
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "kongzYK5caoTnREEQSr7EcSdDOtbrklNKJ4WTZRZRC/fklAylmDE+I23Fb8zkZfFw94LUjAZZ5QDwqjdqnSbddOLZPcd2AFBSQXNgcQlCM2WC3oIgRlHRmOHkOO49uxCLFWAz6wsLKKHTYmA9PYZVvNA73eZs7m/WM8/mjjSTMNar1+FHU7wssm1MMu0TpD3DI5cfb4GU1P7doxDUfAPQVIfQofpHuq/eVV6/D76Bsl8Yjl+ATF0od7y/FeIjnMe4zj0gtmG4JmgBkG25iGT2IVtRpXkWJ+bpiuudQy9K//7pCmNvDPasJSkY8Tq9Loc0VSZOZuYi8U3BAN/j+AHqjgLoYTNhMpzyXlrJDJmvLrlA4FR5bvqsJHlW47pT/vm/+mKG5/xDCNglheyQ04OcLVuF8bMt3fGTlDEYwBicAzRJjOxz89+6S0pqviHDNh0yqdN1ksiuZl6zyGsRc5iNEU3EtZqKLwHCGtPOMOUnTdNPAouK3Ch/6Ged8NRwW1/B2VPutGkH6uZvWFRbyvxydGMNnFCc7h7J/03/l+p3hgFDA2on3w4M5QuJOYDVbMfu+vvolXQ6/RCvRh4D4wCQavEjOxZ0ckcbe1/OVB3f/pofr0VZmTqURVTfuA33sajRET+Jz1onVUayE8+Bzl/glnwAmy8+BXA9lUDMp1BAyI="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "Su3LWczk4dREU/7Feg3txNHPr0mj0zbdaTQB9X7SaQ8tzeK0qULXqjIBiPJDCCSXHOuk6SMD69OBRkTvYnOFalHVRo5qDX/nEn4zje2OeKtK5oD66hkLlyx1ylqx6e3tp6pDJwAKReLgtpZZUR43CqsZZF1FHUY5MyH25B20ylGqpOVhFMwX0MRoqFwkfnW8irF5pxPzqAyW0JT4BLrsCmN6cCkvaL6Iikf4PMYRBGFlV9v/Tu8PbDcV8hxlKx+e+d8owjdzzpZ6fLj2zLQFJDHcBan0T81wzosRdzPfI56tFtKD3osZxw0EYLl+5ykaymJ77DeWEsa1qI8ixVO6a/JB43sv0RCaA3URgTvXoObXHcIZ8RQR9OcjdRCXyaYWsa4N1eY7e4kTb30TUJwAXcHLBSI6QB3Gc6xmKfGg0682/PeQ3zf/QtSyqE9M8USNuUvryOLXXn3FGK0w2MasrjbyY5k8e99awfkj107AyTnQvDvs1MsRppx4pOnEWAhlsr29X71hjOPN5r6Xzm+0Gf8G9L8t1DvUz1ntKlgEtdluHBQ0pJFaj+Rqn3XiJoUntC0Gaa5Le0j8Ps5PDjDtXoU3Yu/dvhH8ocj6KXmFGqxhD609wYY32bTnGAgsND6wXZMVkdY/woqlIySojtxftFurkkDRr41lrVylSA/6GLw="
    on_success: always
    on_failure: always

before_install: pip install --upgrade docker-compose invoke pyyaml

install: inv dc.build

script: true
# inv test

after_success:
- inv ci.tag-build
- inv hub.push
- inv hub.update-readme
