language: python
python:
- "3.6"
services: docker
env:
  global:
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "JBMjwK1/zsgy5QXIjE3lLnQUbYysuNXPAAM68mjv+SKatDYj1JkR5rUkXzPAJFnYYHMGKcgh+vctbQHA+frKHM1Xq9bzRuDQvhjW1M09r/mdggsmQTR964gHbgOCN16ehG3Tu9g5qH1hGNVCl2sX+q4QuxPdTfCKMwRyNLyBrr95CteGqaR0GEcijppU0NvOLINxHR1CyQfZUvr4IKtSxrlxejuLbyHOzylW6gCLJapcovQpVkXSZANitaBTOmuHeBByRYwxx2T59UtNW1Rs22yLNzA124rgdTkF6B8+WVSlgQA6WiGdQ2NsXTwNDFZOoFvv3vB4U+3V8mCO7iZOtyeICFyaY5Mc7w6jW62FLaCzlNRuw6jyQEtHyJvsrXDkcTH1kPFmA77UOTbSBemevaazQQuNTsmpTgr70lVIY5QUlHKwFRK0uUlgYTSThWNtWx6zVw7rBA+8ixnVtqAyA3L2zKQfiTQnfGBeONXLPJUt+EJFZZZBWUns+/MzyHb5Q9CZ2NrLaRcKewCa+ixs2XC01IVDRKCLCchn7kj0ZPgPYwoRRJYOkyJw4Ak8xwutYRzTjWqZbwwaZ4CUiX4amLfxQgcBMzmJRC8ECEOOYznXq1iBGBK4ELNuUjACia23wfYfaqf2qMf5MjcDQf+Jj2sw4iiBlrH+psBOTC9/bSA="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "NvxyW1M0lAdxZ5prrCvJFdc0C0nCEgTQHZMVsS6bFM8sAigNQEP20wv0xtgRwmxviLz9xzmu9wy8pPYm3QbdlEtactMkndH2Z/fW49ZHuVoWMX2LoUXU7EDNE5MtkZDFWzTHw++40zhY7VkYDbDe87Dm7XBjncbWJFv7lUe8K74EYeMjP794JljYQJfLaLQDe6DByhP4eilqCVGNdiHqNLwg6OvGH8hAq41DGwp8qIXOMBd4OWtXID2n+ry3HRG5LZ9febZDwZbuSzMrbihekliSYliw6u1SY25G1E0+psPamyVGhHO6twvyP0v9tQWKlHpQYb64OQXhP1Oc2NmebAdmJqH6F5BaU2eQo7OyE2YmHugmK891bUGSc/0qPt1906zcbtD48wPYbfl1uTSRVTfynTTvn5OazSCD2FudRxQ3PEr3ms/EkvuL1KZLEMilKFelLLGBceq/Y6olesvk3NGDUrV1kcBxKefwPq0qqxx4qyM2hr1+whUj1sdCZ459TL92cq3FaFH0fjUcEzRW4+rtN7oCqT4OcxtLJ3C/HGb2VNoANhq23vYO3fzdMQS8g6eneSAdZv15X5ES1hEIyKekyV0RlnfiOQY8XLAMV1bvMDpDw0zzE1k7NuJhIrQOUu+sWKsOHG39bc34EWWIxIU4xKTV+XZaeIuNctO8Qsk="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

# script: inv test
script: true

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
