version: '3'
services:
  monster-ui:
    container_name: monster-ui
    build:
      context: images/monster-ui
      args:
        MONSTER_UI_TAG: '4.1.56'
        MONSTER_APPS: accounts,callflows,fax,numbers,pbxs,voip,voicemails,webhooks
        TMPLD_VERSION: '0.2.3'
    image: "telephoneorg/monster-ui:${DOCKER_TAG:-latest}"
    environment:
      NGINX_PROXY_PROTOCOL: 'false'
      NGINX_LOG_LEVEL: warn
      MONSTERUI_CROSSBAR_URI: http://localhost:8000/v2/
      MONSTERUI_WEBSOCKET_URI: ws://localhost:5555
      MONSTERUI_WEBPHONE_URI: ws://localhost:5064
      MONSTERUI_DISABLE_BRAINTREE: 'false'
      MONSTERUI_SHOW_JS_ERRORS: 'true'
    ports:
    - "80:80"
    networks:
      kazoo:
  kazoo:
    container_name: kazoo
    hostname: kazoo.local
    image: telephoneorg/kazoo:latest
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
      RABBITMQ_HOSTS: rabbitmq.kazoo
      COUCHDB_HOST: couchdb.kazoo
      COUCHDB_USER: admin
      COUCHDB_PASS: secret
      KAZOO_LOG_LEVEL: info
      KAZOO_APPS: blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,fax,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    tmpfs:
    - /tmp
    networks:
      kazoo:
        aliases:
        - kazoo.kazoo
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.kazoo
    image: telephoneorg/rabbitmq:latest
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
    tmpfs:
    - /var/lib/rabbitmq/mnesia
    networks:
      kazoo:
        aliases:
        - rabbitmq.kazoo
  couchdb:
    container_name: couchdb
    hostname: couchdb.kazoo
    image: telephoneorg/couchdb:latest
    environment:
      ERLANG_HOSTNAME: long
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: chnage-me
      COUCHDB_SHARDS: 1
      COUCHDB_LOG_LEVEL: warn
    volumes_from:
    - couchdb-data-preset
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      kazoo:
        aliases:
        - couchdb.kazoo
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
  couchdb-data-preset:
    image: telephoneorg/couchdb-data-preset:latest
networks:
  kazoo:
