apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    project: telephoneorg
    environment: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: monster-ui
        project: telephoneorg
        environment: production
    spec:
      initContainers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - kazoo
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: dl-assets
        image: telephoneorg/kzutil:latest
        imagePullPolicy: Always
        args:
        - dl-assets
        - monster-apps-core
        - monster-apps-custom
        env:
        - name: MONSTER_APPS_CORE_TAG
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: kzutil.monster-apps.core.tag
        - name: MONSTER_APPS_CUSTOM_TAG
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: kzutil.monster-apps.custom.tag
        - name: GITHUB_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
        volumeMounts:
        - name: monster-ui
          mountPath: /var/www/html/monster-ui
      containers:
      - name: monster-ui
        image: telephoneorg/monster-ui:latest
        imagePullPolicy: Always
        env:
        - name: NGINX_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: nginx.log.level
        - name: NGINX_HTTP_CLIENT_MAX_BODY_SIZE
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: nginx.http-client.max-body-size
        - name: NGINX_LOAD_BALANCER_CIDR
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: nginx.load-balancer.cidr
        - name: MONSTERUI_CROSSBAR_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.crossbar.uri
        - name: MONSTERUI_WEBSOCKET_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.websocket.uri
        - name: MONSTERUI_WEBPHONE_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.webphone.uri
        - name: MONSTERUI_DISABLE_BRAINTREE
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.disable-braintree
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: monster-ui
          mountPath: /var/www/html/monster-ui
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: monster-ui
        emptyDir: {}
      restartPolicy: Always
