apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my.valuphone.com
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
  labels:
    app: monster-ui
    project: telephoneorg
    environment: production
    domain: my.valuphone.com
spec:
  tls:
  - hosts:
    - my.valuphone.com
    secretName: my.valuphone.com-tls
  rules:
  - host: my.valuphone.com
    http:
      paths:
      - path: /
        backend:
          serviceName: monster-ui
          servicePort: 80
