# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: my.telephone.org
#   annotations:
#     kubernetes.io/tls-acme: 'true'
#     kubernetes.io/ingress.class: 'nginx'
#   labels:
#     app: monster-ui
#     project: telephoneorg
#     environment: production
#     domain: my.telephone.org
# spec:
#   tls:
#   - hosts:
#     - my.telephone.org
#     secretName: my.telephone.org-tls
#   rules:
#   - host: my.telephone.org
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: monster-ui
#           servicePort: 80
