apiVersion: v1
kind: Service
metadata:
  name: monsterui
  labels:
    app: monsterui
    project: telephoneorg
    environment: production
spec:
  selector:
    app: monsterui
    project: telephoneorg
    environment: production
  ports:
  - name: http
    port: 80
