apiVersion: v1
kind: ConfigMap
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    project: telephoneorg
    environment: production
data:
  nginx.log.level: warn
  nginx.http-client.max-body-size: 50M
  nginx.load-balancer.cidr: '0.0.0.0/0'
  monsterui.crossbar.uri: //api.valuphone.com/v2/
  monsterui.websocket.uri: //wss.telephoneorg.com
  monsterui.webphone.uri: //wss.telephoneorg.com:5065
  monsterui.disable-braintree: 'false'
