apiVersion: v1
kind: Service
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    project: telephoneorg
    environment: production
spec:
  selector:
    app: monster-ui
    project: telephoneorg
    environment: production
  ports:
  - name: http
    port: 80
