#!/bin/bash -l

set -e

[[ -f /etc/entrypoint ]] && . /etc/entrypoint
# need to source and export any shell vars to the environment now that tmpld is
# writing the templates from the environment.
for dir in $APP nginx; do
    if [[ -f /etc/default/$dir ]]; then
        source /etc/default/$dir
        export $(grep -v '^#' /etc/default/$dir | cut -d'=' -f1 | xargs)
    fi
done


log::m-info "Writing config templates ..."
if [[ -d /config || -L /config ]]; then
    tmpld /config/*.j2
else
    tmpld /templates/*.j2
fi


log::m-info "Starting nginx & $APP ..."
cd ~
    exec nginx
