apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monsterui
  labels:
    app: monsterui
    project: valuphone
    role: user-interface
spec:
  replicas: 3
  selector:
    app: monsterui
    project: valuphone
  template:
    metadata:
      name: monsterui
      labels:
        app: monsterui
        project: valuphone
    spec:
      containers:
        - name: monsterui
          image: callforamerica/monsterui
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
          imagePullPolicy: Always
        - name: dns
          image: callforamerica/go-dnsmasq
      restartPolicy: Always