kind: Pod
apiVersion: v1
metadata:
  name: monsterui
  labels:
    app: monsterui
    project: valuphone
    role: user-interface
spec:
  containers:
    - name: monsterui
      image: callforamerica/monsterui
      imagePullPolicy: Always
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
      resources:
        requests:
          cpu: 2
          memory: 1G
        limits:
          cpu: 2
          memory: 1G 
      readinessProbe:
        httpGet:
          path: /monster-ui
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 3
      livenessProbe:
        httpGet:
          path: /monster-ui
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 3
  restartPolicy: Always
