kind: Service
apiVersion: v1
metadata: 
  name: monsterui
spec:
  selector:
    app: monsterui
    project: valuphone
    environment: production
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
