apiVersion: v1
kind: ReplicationController
metadata:
  name: monsterui
spec:
  replicas: 1
  template:
    metadata:
      name: monsterui
      labels:
        app: monsterui
        project: valuphone
        environment: production
    spec:
      containers:
        - name: monsterui
          image: callforamerica/monsterui
          env:
            - name: NGINX_LOG_LEVEL
              value: info
            - name: CROSSBAR_URI
              value: https://api.valuphone.com:8443
            - name: ENABLE_SMARTPBX_CALLFLOWS
              value: 'true'
            - name: DISABLE_BRAINTREE
              value: 'false'
            - name: COMPANY_NAME
              value: Valuphone
            - name: APPLICATION_TITLE
              value: Valuphone
            - name: CALL_REPORT_EMAIL
              value: support@valuphone.com  
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G 
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 15
          imagePullPolicy: Always
      restartPolicy: Always