apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monsterui
spec:
  replicas: 1
  template:
    metadata:
      name: monsterui
      labels:
        app: monsterui
        project: valuphone
        environment: production
    spec:
      containers:
      - name: monsterui
        image: callforamerica/monsterui
        env:
        - name: NGINX_LOG_LEVEL
          valueFrom:
            configMap:
              name: sup-config
              key: nginx.log-level
        - name: NGINX_ACCESS_LOG
          valueFrom:
            configMap:
              name: monsterui-config
              key: nginx.access-log
        - name: CROSSBAR_URI
          valueFrom:
            configMap:
              name: environment-config
              key: crossbar.external.uri  
        - name: ENABLE_WEBSOCKETS
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.enable-websockets                   
        - name: WEBSOCKETS_URI
          valueFrom:
            configMap:
              name: environment-config
              key: websockets.external.uri
        - name: ENABLE_SOCKET_WEBPHONE
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.enable-socket-webphone                   
        - name: SOCKET_WEBPHONE_URI
          valueFrom:
            configMap:
              name: environment-config
              key: monsterui.socket-webphone.uri
        - name: ENABLE_PROVISIONER
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.enable-provisioner
        - name: PROVISIONER_URI
          valueFrom:
            configMap:
              name: environent-config
              key: provisioner.uri
        - name: ENABLE_PHONEBOOK
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.enable-phonebook
        - name: PHONEBOOK_URI
          valueFrom:
            configMap:
              name: environment-config
              key: phonebook.uri
        - name: DISABLE_BRAINTREE
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.disable-braintree
        - name: MONSTERUI_LOGOUT_TIMER
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.logout-timer
        - name: APPLICATION_TITLE
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.application-title
        - name: COMPANY_NAME
          valueFrom:
            configMap:
              name: company-config
              key: company.name
        - name: CALL_REPORT_EMAIL
          valueFrom:
            configMap:
              name: company-config
              key: company.support.email
        - name: LOGOUT_URL
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.logout-url
        - name: SHOW_JS_ERRORS
          valueFrom:
            configMap:
              name: monsterui-config
              key: monsterui.show-js-errors
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        resources:
          requests:
            cpu: 2
            memory: 1G
          limits:
            cpu: 2
            memory: 1G 
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 15
        imagePullPolicy: Always
    restartPolicy: Always