apiVersion: v1
kind: ConfigMap
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    test: 'true'
    environment: testing
data:
  nginx.log.level: warn
  nginx.proxy-protocol: 'false'
  monster-ui.crossbar.uri: //minikube.telephoneorg.local:30800/v2/
  monster-ui.websocket.uri: ws://minikube.telephoneorg.local:30055
  monster-ui.webphone.uri: ws://minikube.telephoneorg.local:5064
  monster-ui.disable-braintree: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    test: 'true'
    environment: testing
spec:
  type: NodePort
  selector:
    app: monster-ui
  ports:
  - name: http
    port: 80
    nodePort: 30080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monster-ui
  labels:
    app: monster-ui
    test: 'true'
    environment: testing
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: monster-ui
        test: 'true'
        environment: testing
    spec:
      initContainers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - kazoo
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: monster-ui
        image: telephoneorg/monster-ui:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NGINX_PROXY_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: nginx.proxy-protocol
        - name: NGINX_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: nginx.log.level
        - name: MONSTERUI_CROSSBAR_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.crossbar.uri
        - name: MONSTERUI_WEBSOCKET_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.websocket.uri
        - name: MONSTERUI_WEBPHONE_URI
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.webphone.uri
        - name: MONSTERUI_DISABLE_BRAINTREE
          valueFrom:
            configMapKeyRef:
              name: monster-ui
              key: monster-ui.disable-braintree
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
